apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-app-4433
  name: python-app-4433
spec:
  selector:
    app: python-app-4433
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP