apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-app-4433
  name: python-app-4433
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP